apiVersion: v1
kind: Pod
metadata:
    name: httpserver
    labels:
        app: httpserver
spec:
    containers:
        - name: httpserver
          image: httpserver:latest
          imagePullPolicy: Never
          ports:
              - containerPort: 8080
