apiVersion: "descheduler/v1alpha2"
kind: DeschedulerPolicy
profiles:
  - name: comparative-benchmark
    pluginConfig:
      - name: "DefaultEvictor"
        args:
          ignorePvcPods: false
      - name: "RemovePodsViolatingNodeAffinity"
        args:
          nodeAffinityType:
          - "requiredDuringSchedulingIgnoredDuringExecution"
    plugins:
      deschedule:
        enabled:
          - "RemovePodsViolatingNodeAffinity"
