apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-test
    labels:
        app: deployment-test
spec:
    replicas: 1
    selector:
        matchLabels:
            app: deployment-test
    template:
        metadata:
            labels:
                app: deployment-test
        spec:
            containers:
                - name: nginx
                  image: nginx:1.25-alpine
                  ports:
                      - containerPort: 80
                - name: busybox
                  image: busybox
                  command: ["/bin/sh", "-c", "i=0; while true; do echo $(date) $i; i=$((i+1)); sleep 10; done"]