apiVersion: v1
kind: Pod
metadata:
  name: ssh-server
spec:
  nodeName: k8s-worker
  containers:
  - name: sshd
    image: linuxserver/openssh-server:latest
    env:                         
      - name: PASSWORD_ACCESS
        value: "true"
      - name: USER_PASSWORD
        value: "password"     
    ports:
      - containerPort: 2222
        hostPort: 2222
        name: ssh
